name : 有妖气
domain : u17.com
version : 20120613
book :
    periods : '#chapterlist ul.cf a'
    period_order : asc
    period_name :
        - processor : attr title
    name : 
        - selector : '#workinfo h1'
        - processor : text
        - regexp : '^\s*(\S+)'
    rule : '/comic/\d+\.html'
    props :
        cover : '#workinfo div.cover img'
        author : '#workinfo a[href*=i.u17.com]:eq(0)'
        status : 
            - selector : '#workinfo div.comic'
            - processor : text
            - regexp : '状态：\s*(\S+)'
        cates :
            - selector : '#workinfo div.comic'
            - processor : text
            - regexp : '类别：\s*(\S+)'
        update_time : 
            - selector : '#chapterlist > p:last-child'
            - processor : text
            - regexp : '最后更新时间：\s*([\d-]+)'
        intro : '#workinfo div.intro'    
period :
    rule : '/comic_show/(?<period_id>c\d+_m\d+)(?:_i\d+)?\.html' 
    pages :
        - selector : '#comicShow option'
        - processor : 'attr value | tpl http://www.u17.com/comic_show/{period_id}_i{_}.html' 
page :
    img : 
        - selector : '#SS_cur_pic'
        - processor : attr value
