name : 有妖气
domain : u17.com
version : 20120613
book :
    periods : 'div.comic_chapter_middle > div:first-child > ul a'
    period_order : asc
    period_name :
        - processor : attr title
    name : 'div.address a:last-child'
    rule : '/comic/\d+\.html'
    props :
        cover : 'dt.comic_cover img'
        author : 'dd.comic_info a[href*=i.u17.com]:eq(0)'
        status : 
            - selector : 'dd.comic_info .comic_type'
            - processor : text
            - regexp : '状态：(\S+)'
        cates :
            - selector : 'dd.comic_info .comic_type'
            - processor : text
            - regexp : '类别：(\S+)'
        update_time : 
            - selector : 'div.comic_chapter_top'
            - processor : text
            - regexp : '最后更新时间：([\d-]+)'
        intro : '#comic_description_panel'    
period :
    rule : '/comic_show/(?<period_id>c\d+_m\d+)(?:_i\d+)?\.html' 
    pages :
        - selector : '#comicShow option'
        - processor : 'attr value | tpl http://www.u17.com/comic_show/{period_id}_i{_}.html' 
page :
    img : 
        - selector : '#SS_cur_pic'
        - processor : attr value
